import type { MarkingParams, ShortEntityParams } from '../marking'

export const mockMarkings: MarkingParams[] = [
    {
      id: 1,
      name: 'Футболка мужская',
      article: 'TSHIRT001',
      composition: 'Хлопок 100%',
      client: { id: 1, name: 'ООО "ТекстильПром"' },
      category: 'Одежда',
      color: 'Белый',
      size: 'L',
      barcode: '4601234567890',
      needsChestnyZnakLabel: true,
    },
    {
      id: 2,
      name: 'Джинсы женские',
      article: 'JEANS002',
      composition: 'Хлопок 98%, Эластан 2%',
      client: { id: 2, name: 'ООО "ФэшнГрупп"' },
      category: 'Одежда',
      color: 'Синий',
      size: 'M',
      barcode: '4601234567891',
      needsChestnyZnakLabel: true,
    },
    {
      id: 3,
      name: 'Кроссовки спортивные',
      article: 'SHOES003',
      composition: 'Синтетика, резина',
      client: { id: 3, name: 'ЗАО "ОбувьСпорт"' },
      category: 'Обувь',
      color: 'Чёрный',
      size: '42',
      barcode: '4601234567892',
      needsChestnyZnakLabel: false,
    },
    {
      id: 4,
      name: 'Пальто демисезонное',
      article: 'COAT004',
      composition: 'Шерсть 60%, Полиэстер 40%',
      client: { id: 4, name: 'ИП Иванов И.И.' },
      category: 'Верхняя одежда',
      color: 'Серый',
      size: 'XL',
      barcode: '4601234567893',
      needsChestnyZnakLabel: true,
    },
    {
      id: 5,
      name: 'Рубашка офисная',
      article: 'SHIRT005',
      composition: 'Хлопок 70%, Полиэстер 30%',
      client: { id: 5, name: 'ООО "Стиль и Комфорт"' },
      category: 'Одежда',
      color: 'Голубой',
      size: 'M',
      barcode: '4601234567894',
      needsChestnyZnakLabel: false,
    },
]

export const clients: ShortEntityParams[] = [
  { id: 1, name: 'ООО "ТекстильПром"' },
  { id: 2, name: 'ООО "ФэшнГрупп"' },
  { id: 3, name: 'ЗАО "ОбувьСпорт"' },
  { id: 4, name: 'ИП Иванов И.И.' },
  { id: 5, name: 'ООО "Стиль и Комфорт"' },
]
